DROP DATABASE IF EXISTS blinkdb ;
CREATE DATABASE blinkdb;

DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  email_id VARCHAR(50) PRIMARY KEY,
  token_id TEXT,
  bday VARCHAR(10) NOT NULL
);
